parser.js: vb.language
	@echo "/* Parser generated by language.js (see Makefile) */" > parser.js
	language -g vb.language >> parser.js

# PEG.js reports errors better than language.js, let's run it before testing
test/pegjs_parser.js: vb.language test/pegjs_build
	test/pegjs_build vb.language test/pegjs_parser.js

test: test/pegjs_parser.js parser.js
    # Usage:
    #     $ make test TEST="grep pattern"
    ifdef TEST
	env TESTING=1 mocha --compilers coffee:coffee-script -u tdd -g "$(TEST)"
    else
	env TESTING=1 mocha --compilers coffee:coffee-script -u tdd
    endif

.PHONY: test
