# TODO use `language -t` to stop repeating generated parser code
%.parser.js : %.language common.language
	@echo "/* Generated by language.js (see Makefile) */" > $@
	cat $< | ./preprocess | language >> $@

# PEG.js reports errors better than language.js, let's run it before testing
test/%.peg.js: %.language common.language test/pegjs_build
	cat $< | ./preprocess | test/pegjs_build $<_preprocessed > $@

test: test/vb.peg.js vb.parser.js test/expr.peg.js expr.parser.js
    # Usage:
    #     $ make test TEST="grep pattern"
    ifdef TEST
	env TESTING=1 mocha --compilers coffee:coffee-script -u tdd -g "$(TEST)"
    else
	env TESTING=1 mocha --compilers coffee:coffee-script -u tdd
    endif

.PHONY: test
